image: Visual Studio 2019

# Turn off default msbuild integration
build: false
version: 0.2.{build}

environment:
  bintray_user:
    secure: u2gaErEDY6qCasVxS+318Q==
  bintray_key:
    secure: 4wMikiVBJ3a6hXGBN7N7iYrntdzgeBEmYsTesxP2sQ0F/YL2MTChs7qHVNXo52pa

init:
  - ps: ls -Name "c:\\python*"
  - "SET PATH=\\Python38;\\Python38\\Scripts;%PATH%"

install:
  - ps: ls -name "C:\\Python38\\Lib\\site-packages"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade pip"
  - "pip --version"
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - "pip install pipenv"
  - "python -m venv .venv"
  - ps: .venv\Scripts\activate.ps1
  - "pip install -r development.txt"
  - "python setup_freeze.py build"
  - cd build/exe.win32-3.8
  - ps: $env:pomito_zip = "pomito.$($env:APPVEYOR_BUILD_VERSION).win32.zip"
  - ps: "& 7z a -r ../$env:pomito_zip ."
  - ps: if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $pomito_path = $(Resolve-Path "../$env:pomito_zip"); curl.exe -fsS -k -u "$($env:bintray_user):$env:bintray_key" -X PUT "https://api.bintray.com/content/codito/generic/pomito/$env:APPVEYOR_BUILD_VERSION/$($env:pomito_zip)?publish=1" --data-binary "@$pomito_path" }

on_finish:
  - cd /D %APPVEYOR_BUILD_FOLDER%

test_script:
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - ps: .venv\Scripts\activate.ps1
  - "pytest"

artifacts:
  - path: build/*.zip

deploy: off
