sudo: false
language: python

python:
  - "3.4"

env:
  - "POMITO_TEST=1"

install:
  - "pip install -r requirements.txt"
  - "pip freeze"

script: nosetests

after_success: coveralls
