sudo: false
language: python
cache: pip

python:
  - "3.6"

env:
  - "POMITO_TEST=1"

install:
  - pip install pipenv
  - pipenv check
  - pipenv install --dev --verbose

script: pipenv run pytest

after_success: pipenv run coveralls
