sudo: false
language: python
cache: pip

python:
  - "3.6"

env:
  - "POMITO_TEST=1"

install:
  - pip install pipenv
  - pipenv install --dev

script: pipenv run nosetests

after_success: pipenv run coveralls
