language: python
python:
  - "3.3"

# command to install dependencies
install:
    - pip install -r requirements.txt
  - python setup.py build sdist

# command to run tests
script: nosetests --verbosity 2
