sudo: false
language: python
cache: pip

python:
  - "3.6"

env:
  - "POMITO_TEST=1"

install:
  - "pip install -r requirements.txt"
  - "pip freeze"

script: nosetests

after_success: coveralls
