os: Windows Server 2012 R2

deploy: off

init:
  - echo "Filesystem root:"
  - ps: "ls -Name \"C:/\""
  - echo "Installed SDKs:"
  - ps: "ls -Name \"C:/Program Files/Microsoft SDKs/Windows\""
  - echo "Set python path"
  - "SET PATH=\\Python34;\\Python34\\Scripts;%PATH%"

install:
  - ps: Start-FileDownload "http://downloads.sourceforge.net/pyqt/PyQt5/PyQt-5.3.2/PyQt5-5.3.2-gpl-Py3.4-Qt5.3.1-x32.exe" -FileName $env:temp/pyqt5_install.exe
  - ps: "& $env:temp/pyqt5_install.exe /S"
  - ps: "Wait-Process -Name pyqt5_install -Timeout 600"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -c \"import PyQt5\""
  - "pip --version"

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "pip install -r requirements.txt"
  - "python setup.py build"

test_script:
  - "nosetests"

artifacts:
  - path: build\exe.win32-3.4
    name: pomito.{version}.win32
    type: zip
